---
- hosts: spcodes.rd.tp-link.net
  remote_user: spcodes
  tasks:
    - name: create backup directory
      file: path=/tmp/backup state=directory mode=0777
    - name: change filemode of src directry
      shell: sudo chmod -R 777 /var/opt/gitlab/backups
    - name: remove old backup
      file: path=/var/opt/gitlab/backups/* state=absent
    - name: excute rake to bacpup files
      shell: sudo gitlab-rake gitlab:backup:create
    - name: backup tgz files
      archive: dest=/tmp/backup/gitlab_latest.tgz path=/var/opt/gitlab/backups remove=yes
    - name: get remote backup file to local area
      fetch: src=/tmp/backup/gitlab_latest.tgz  dest=/backup
    - name: delete backup files on remote host
      file: path=/tmp/backup state=absent
...